const swaggerSpec = {
  openapi: '3.0.3',
  info: {
    title: 'BarberOsbao API',
    version: '0.1.0',
    description: 'Minimal API for BarberOsbao generated by scaffold',
  },
  servers: [{ url: 'http://localhost:3000' }],
  paths: {
    '/auth/register': { post: { summary: 'Register user' } },
    '/auth/login': { post: { summary: 'Login' } },
    '/clients': { get: { summary: 'List clients' }, post: { summary: 'Create client' } },
    '/appointments': { get: { summary: 'List appointments' }, post: { summary: 'Create appointment' } },
    '/services': { get: { summary: 'List services' }, post: { summary: 'Create service' } },
    '/payments': { get: { summary: 'List payments' }, post: { summary: 'Create payment' } }
  }
};

// Add simple components/schemas
swaggerSpec.components = {
  schemas: {
    Service: {
      type: 'object',
      properties: { id: { type: 'string' }, title: { type: 'string' }, price: { type: 'number' }, durationMin: { type: 'integer' } }
    },
    Client: { type: 'object', properties: { id: { type: 'string' }, name: { type: 'string' }, phone: { type: 'string' }, email: { type: 'string' } } },
    Appointment: { type: 'object', properties: { id: { type: 'string' }, clientId: { type: 'string' }, serviceId: { type: 'string' }, startAt: { type: 'string' }, endAt: { type: 'string' } } },
    Payment: { type: 'object', properties: { id: { type: 'string' }, appointmentId: { type: 'string' }, amount: { type: 'number' }, method: { type: 'string' } } }
  }
};

export default swaggerSpec;
