const swaggerSpec = {
  openapi: '3.0.3',
  info: {
    title: 'BarberOsbao API',
    version: '0.1.0',
    description: 'Minimal API for BarberOsbao generated by scaffold',
  },
  servers: [{ url: 'http://localhost:3000' }],
  paths: {
    '/auth/register': { post: { summary: 'Register user' } },
    '/auth/login': { post: { summary: 'Login' } },
    '/clients': { get: { summary: 'List clients' }, post: { summary: 'Create client' } },
    '/appointments': { get: { summary: 'List appointments' }, post: { summary: 'Create appointment' } },
    '/services': { get: { summary: 'List services' }, post: { summary: 'Create service' } },
    '/payments': { get: { summary: 'List payments' }, post: { summary: 'Create payment' } }
  }
};

export default swaggerSpec;
